name       : hashcat
version    : 6.2.2
release    : 9
source     :
    - https://github.com/hashcat/hashcat/archive/refs/tags/v6.2.2.tar.gz : 0e34c47f7505c4efb885cf893083386ee847d508f5711906281071f14a1c7a75
license    : MIT
component  : security.crypto
libsplit   : no
summary    : World's fastest and most advanced password recovery utility
description: |
    hashcat is the world's fastest and most advanced password recovery utility, supporting five unique modes of attack for over 200 highly-optimized hashing algorithms. hashcat currently supports CPUs, GPUs, and other hardware accelerators.
builddeps  :
    - opencl-headers
    - xxhash-devel
rundeps    :
    - ocl-icd
build      : |
    %make SHARED=1 USE_SYSTEM_OPENCL=1 USE_SYSTEM_XXHASH=1 PREFIX=/usr
install    : |
    %make_install SHARED=1 USE_SYSTEM_OPENCL=1 USE_SYSTEM_XXHASH=1 PREFIX=/usr
