name       : hashcat
version    : 4.1.0
release    : 2
source     :
    - https://github.com/hashcat/hashcat/archive/v4.1.0.tar.gz : bd23997153c5a8c8b35da3931ff74a808561399de3f3e07058ff4d2f8617119c
license    : MIT
component  : security.crypto
libsplit   : no
summary    : World's fastest and most advanced password recovery utility
description: |
    hashcat is the world's fastest and most advanced password recovery utility, supporting five unique modes of attack for over 200 highly-optimized hashing algorithms. hashcat currently supports CPUs, GPUs, and other hardware accelerators.
builddeps  :
    - opencl-headers
rundeps    :
    - beignet
    - ocl-icd
build      : |
    %make SHARED=1 PREFIX=/usr
install    : |
    %make_install SHARED=1 PREFIX=/usr
