name       : hashcat
version    : 4.0.0
release    : 1
source     :
    - https://github.com/hashcat/hashcat/archive/v4.0.0.tar.gz : e14c169d6966830e7b7423e17e678f3333e074ec50dae50bdde40e8e0e8658be
license    : MIT
component  : security.crypto
libsplit   : no
summary    : World's fastest and most advanced password recovery utility
description: |
    hashcat is the world's fastest and most advanced password recovery utility, supporting five unique modes of attack for over 200 highly-optimized hashing algorithms. hashcat currently supports CPUs, GPUs, and other hardware accelerators.
builddeps  :
    - beignet-devel
rundeps    :
    - ocl-icd
setup      : |
    %patch -p1 < $pkgfiles/0001-fix-VERSION_TAG-compilation-problem.patch
build      : |
    %make SHARED=1 PREFIX=/usr
install    : |
    %make_install SHARED=1 PREFIX=/usr
