name       : hashcat
version    : 6.2.1
release    : 8
source     :
    - https://github.com/hashcat/hashcat/archive/refs/tags/v6.2.1.tar.gz : 4994e9ee8ef050881d5c7986b2b95a3abf2114f79e4dbaa28a537f8e2ad5c93b
license    : MIT
component  : security.crypto
libsplit   : no
summary    : World's fastest and most advanced password recovery utility
description: |
    hashcat is the world's fastest and most advanced password recovery utility, supporting five unique modes of attack for over 200 highly-optimized hashing algorithms. hashcat currently supports CPUs, GPUs, and other hardware accelerators.
builddeps  :
    - opencl-headers
    - xxhash-devel
rundeps    :
    - ocl-icd
build      : |
    %make SHARED=1 USE_SYSTEM_OPENCL=1 USE_SYSTEM_XXHASH=1 PREFIX=/usr
install    : |
    %make_install SHARED=1 USE_SYSTEM_OPENCL=1 USE_SYSTEM_XXHASH=1 PREFIX=/usr
