name       : hashcat
version    : 6.0.0
release    : 5
source     :
    - https://github.com/hashcat/hashcat/archive/v6.0.0.tar.gz : e8e70f2a5a608a4e224ccf847ad2b8e4d68286900296afe00eb514d8c9ec1285
license    : MIT
component  : security.crypto
libsplit   : no
summary    : World's fastest and most advanced password recovery utility
description: |
    hashcat is the world's fastest and most advanced password recovery utility, supporting five unique modes of attack for over 200 highly-optimized hashing algorithms. hashcat currently supports CPUs, GPUs, and other hardware accelerators.
builddeps  :
    - opencl-headers
    - xxhash-devel
rundeps    :
    - beignet
    - ocl-icd
build      : |
    %make SHARED=1 USE_SYSTEM_OPENCL=1 USE_SYSTEM_XXHASH=1 PREFIX=/usr
install    : |
    %make_install SHARED=1 USE_SYSTEM_OPENCL=1 USE_SYSTEM_XXHASH=1 PREFIX=/usr
